name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]

jobs:
  secure-deploy:
    name: Terraform + Checkov + CloudSploit
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Checkov - Pre-deployment scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform
          config_file: .checkov.yaml
          # config_file: .checkov-skippedfailcase.yaml 

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: CloudSploit - Post-deployment Scan
        run: |
          chmod +x cloudsploit_scan.sh
          ./cloudsploit_scan.sh

      - name: Terraform Destroy - Cleanup
        if: always()
        working-directory: terraform
        run: terraform destroy -auto-approve
